const $=s=>document.querySelector(s); const log=(...a)=>{$('#log').textContent+=a.join(' ')+'\n'};
ort.env.wasm.wasmPaths='https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/'; ort.env.wasm.numThreads=1;
let regionDet,tileDet,cls,classes,imgBitmap;
const JP={'0m':'赤5萬','0p':'赤5筒','0s':'赤5索','0z':'赤白','1z':'東','2z':'南','3z':'西','4z':'北','5z':'白','6z':'發','7z':'中','back':'裏'};
function label(c){if(JP[c])return JP[c]; const n=c[0],s=c[1]; return n+({m:'萬',p:'筒',s:'索'}[s]||s)}
async function loadModels(){try{
 $('#status').textContent='モデル読込中…'; classes=await (await fetch('models/mahjong-classes.json',{cache:'no-store'})).json();
 const parts=await (await fetch('models/data-parts.json',{cache:'no-store'})).json(); let blobs=[],total=0;
 for(let i=0;i<parts.length;i++){ $('#status').textContent=`分類器データ読込 ${i+1}/${parts.length}`; const b=await (await fetch('models/'+parts[i],{cache:'no-store'})).blob(); blobs.push(b); total+=b.size; }
 const ext=new Blob(blobs,{type:'application/octet-stream'}); blobs=[]; log('classifier external data',(total/1048576).toFixed(1),'MB');
 regionDet=await ort.InferenceSession.create('models/regions-yolo-26n.onnx',{executionProviders:['wasm']});
 tileDet=await ort.InferenceSession.create('models/tile-yolo-26n.onnx',{executionProviders:['wasm']});
 cls=await ort.InferenceSession.create('models/classifier-resnet50.onnx',{executionProviders:['wasm'],externalData:[{path:'classifier-resnet50.onnx.data',data:ext}]});
 log('region',JSON.stringify(regionDet.inputNames),'->',JSON.stringify(regionDet.outputNames)); log('tile',JSON.stringify(tileDet.inputNames),'->',JSON.stringify(tileDet.outputNames)); log('cls',JSON.stringify(cls.inputNames),'->',JSON.stringify(cls.outputNames));
 $('#status').textContent='3モデル読込完了。写真を選択してください。';
}catch(e){$('#status').textContent='モデル読込失敗: '+e.message;log(e.stack||e)}}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;imgBitmap=await createImageBitmap(f);$('#preview').src=URL.createObjectURL(f);$('#preview').style.display='block';$('#run').disabled=!(regionDet&&tileDet&&cls);$('#status').textContent=`画像 ${imgBitmap.width}×${imgBitmap.height}`};
function letterbox(src,size=640){const sw=src.width,sh=src.height,c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle='rgb(114,114,114)';x.fillRect(0,0,size,size);const sc=Math.min(size/sw,size/sh),w=sw*sc,h=sh*sc,dx=(size-w)/2,dy=(size-h)/2;x.drawImage(src,dx,dy,w,h);const d=x.getImageData(0,0,size,size).data,a=new Float32Array(3*size*size);for(let i=0;i<size*size;i++){a[i]=d[i*4]/255;a[size*size+i]=d[i*4+1]/255;a[2*size*size+i]=d[i*4+2]/255}return{tensor:new ort.Tensor('float32',a,[1,3,size,size]),sc,dx,dy,sw,sh}}
function iou(a,b){const x=Math.max(a.x1,b.x1),y=Math.max(a.y1,b.y1),X=Math.min(a.x2,b.x2),Y=Math.min(a.y2,b.y2),inter=Math.max(0,X-x)*Math.max(0,Y-y),aa=(a.x2-a.x1)*(a.y2-a.y1),bb=(b.x2-b.x1)*(b.y2-b.y1);return inter/(aa+bb-inter+1e-9)}
function nms(rows,thr=.45){rows.sort((a,b)=>b.score-a.score);const keep=[];for(const r of rows)if(!keep.some(k=>iou(k,r)>thr))keep.push(r);return keep}
function parseRegion(t,meta){const d=t.data,sh=t.dims;if(sh.length!==3)throw new Error('Region出力形状 '+JSON.stringify(sh));let C,N,at;if(sh[1]<100){C=sh[1];N=sh[2];at=(n,c)=>d[c*N+n]}else{N=sh[1];C=sh[2];at=(n,c)=>d[n*C+c]}const nc=C-4;log('=== REGION ===');log('shape',JSON.stringify(sh),'classes',nc);let rows=[];for(let n=0;n<N;n++){let best=-Infinity,ci=-1;for(let c=0;c<nc;c++){const s=at(n,4+c);if(s>best){best=s;ci=c}}if(best<0.20||ci!==0)continue;const x=at(n,0),y=at(n,1),w=at(n,2),h=at(n,3);let x1=(x-w/2-meta.dx)/meta.sc,y1=(y-h/2-meta.dy)/meta.sc,x2=(x+w/2-meta.dx)/meta.sc,y2=(y+h/2-meta.dy)/meta.sc;x1=Math.max(0,x1);y1=Math.max(0,y1);x2=Math.min(meta.sw,x2);y2=Math.min(meta.sh,y2);if(x2>x1&&y2>y1)rows.push({x1,y1,x2,y2,score:best,cls:ci})}rows=nms(rows,.45);log('self_hand candidates',rows.length,rows.map(r=>r.score.toFixed(3)).join(','));if(!rows.length)return null;rows.sort((a,b)=>b.score-a.score);return rows[0]}
function cropSource(src,r,pad=.10){const sw=src.width,sh=src.height,p=pad*Math.max(r.x2-r.x1,r.y2-r.y1),sx=Math.max(0,r.x1-p),sy=Math.max(0,r.y1-p),ex=Math.min(sw,r.x2+p),ey=Math.min(sh,r.y2+p);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(ex-sx));c.height=Math.max(1,Math.round(ey-sy));c.getContext('2d').drawImage(src,sx,sy,ex-sx,ey-sy,0,0,c.width,c.height);return c}
function parseTiles(t,meta){const d=t.data,sh=t.dims;log('=== TILE ===');log('shape',JSON.stringify(sh));let N,C,at;if(sh[1]===37){C=37;N=sh[2];at=(n,c)=>d[c*N+n]}else if(sh[2]===37){N=sh[1];C=37;at=(n,c)=>d[n*C+c]}else throw new Error('Tile output '+JSON.stringify(sh));let rows=[];for(let n=0;n<N;n++){const score=at(n,4);if(!Number.isFinite(score)||score<0.20)continue;const x=at(n,0),y=at(n,1),w=at(n,2),h=at(n,3);let x1=(x-w/2-meta.dx)/meta.sc,y1=(y-h/2-meta.dy)/meta.sc,x2=(x+w/2-meta.dx)/meta.sc,y2=(y+h/2-meta.dy)/meta.sc;x1=Math.max(0,x1);y1=Math.max(0,y1);x2=Math.min(meta.sw,x2);y2=Math.min(meta.sh,y2);const bw=x2-x1,bh=y2-y1;if(bw<5||bh<5)continue;rows.push({x1,y1,x2,y2,score,cx:(x1+x2)/2,cy:(y1+y2)/2,bw,bh})}log('raw tile candidates',rows.length);rows=nms(rows,.45);log('after tile NMS',rows.length);if(rows.length>18)rows=rows.sort((a,b)=>b.score-a.score).slice(0,18);rows.sort((a,b)=>a.cx-b.cx);log('final tiles',rows.length);return rows}
function tile224(src,r){const p=.04*Math.max(r.x2-r.x1,r.y2-r.y1),sx=Math.max(0,r.x1-p),sy=Math.max(0,r.y1-p),ex=Math.min(src.width,r.x2+p),ey=Math.min(src.height,r.y2+p),sw=ex-sx,sh=ey-sy,c=document.createElement('canvas');c.width=c.height=224;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,224,224);const sc=Math.min(224/sw,224/sh),dw=sw*sc,dh=sh*sc;x.drawImage(src,sx,sy,sw,sh,(224-dw)/2,(224-dh)/2,dw,dh);return c}
function classTensor(c){const d=c.getContext('2d').getImageData(0,0,224,224).data,a=new Float32Array(3*224*224),mean=[.485,.456,.406],std=[.229,.224,.225];for(let i=0;i<224*224;i++)for(let k=0;k<3;k++)a[k*224*224+i]=(d[i*4+k]/255-mean[k])/std[k];return new ort.Tensor('float32',a,[1,3,224,224])}
async function classify(c){const o=await cls.run({[cls.inputNames[0]]:classTensor(c)}),v=o[cls.outputNames[0]].data;let mx=-Infinity,ix=0;for(let i=0;i<v.length;i++)if(v[i]>mx){mx=v[i];ix=i}let sum=0;for(const z of v)sum+=Math.exp(z-mx);return{conf:1/sum,code:classes[ix]}}
$('#run').onclick=async()=>{if(!imgBitmap)return;try{$('#run').disabled=true;$('#tiles').innerHTML='';$('#count').textContent='';log('--- run v5 ---');$('#status').textContent='① 手牌領域を検出中…';const rm=letterbox(imgBitmap);const ro=await regionDet.run({[regionDet.inputNames[0]]:rm.tensor});const rt=ro['output0']||ro[regionDet.outputNames[0]];const hand=parseRegion(rt,rm);if(!hand)throw new Error('self_hand（自分の手牌領域）を検出できませんでした');log('selected self_hand',hand.score.toFixed(3),Math.round(hand.x1),Math.round(hand.y1),Math.round(hand.x2),Math.round(hand.y2));const handCanvas=cropSource(imgBitmap,hand,.08);$('#status').textContent=`② 手牌領域 ${handCanvas.width}×${handCanvas.height} → 牌を検出中…`;const tm=letterbox(handCanvas);const to=await tileDet.run({[tileDet.inputNames[0]]:tm.tensor});const tt=to['output0']||to[tileDet.outputNames[0]];const boxes=parseTiles(tt,tm);$('#count').textContent=`${boxes.length}枚`;if(!boxes.length)throw new Error('手牌領域内で牌を検出できませんでした');for(let i=0;i<boxes.length;i++){ $('#status').textContent=`③ 牌種を分類中 ${i+1}/${boxes.length}`;const c=tile224(handCanvas,boxes[i]),p=await classify(c),card=document.createElement('div');card.className='tile';card.appendChild(c);card.insertAdjacentHTML('beforeend',`<b>${label(p.code)}</b><small>${p.code} / ${(p.conf*100).toFixed(1)}%<br>検出 ${(boxes[i].score*100).toFixed(1)}%</small>`);$('#tiles').appendChild(card)}$('#status').textContent=`完了：self_hand → ${boxes.length}枚検出 → 分類完了`;log('completed',boxes.length);}catch(e){$('#status').textContent='認識失敗: '+e.message;log(e.stack||e)}finally{$('#run').disabled=false}};
loadModels();
